const Constants = {
    statuses: {
        lowCongestion: 'Low congestion',
        congested: 'Congested, stay alert',
        avoid: 'Avoid',
        noStatus: 'Status not available',
    },
    bbq: {
        afterSix: 'Only allowed after 6pm',
        designedArea: 'Permitted in the designated area only',
        notAllowed: 'Not allowed',
    },
    parking: {
        availability: 'Parking availability: ',
        notAvailable: 'No parking at this beach',
    },
};

const beaches = [
    {
        id: 0,
        name: 'Alum Chine',
        beachStatus: Constants.statuses.lowCongestion,
        latitude: 50.711087,
        longitude: -1.895755,
        latitudeParking: 50.71485,
        longitudeParking: -1.890675,
        lifeguarded: false,
        publicToilets: true,
        parkingAvailability: Constants.parking.notAvailable,
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.afterSix,
        warningInfo: '',
        imagePath: require('./assets/beaches/alumn_chine.png'),
    },
    {
        id: 1,
        name: 'Avon Beach',
        beachStatus: Constants.statuses.noStatus,
        latitude: 50.731404,
        longitude: -1.731441,
        latitudeParking: 50.728744,
        longitudeParking: -1.73491,
        lifeguarded: false,
        publicToilets: true,
        parkingAvailability: Constants.parking.availability + '67%',
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.afterSix,
        warningInfo: '',
        imagePath: require('./assets/beaches/avon.png'),
    },
    {
        id: 2,
        name: 'Boscombe Beach East',
        latitude: 50.719996,
        longitude: -1.841179,
        latitudeParking: 50.720522,
        longitudeParking: -1.842338,
        beachStatus: Constants.statuses.avoid,
        lifeguarded: false,
        publicToilets: true,
        parkingAvailability: Constants.parking.notAvailable,
        dogWalking: false,
        cycling: false,
        bbq: Constants.bbq.afterSix,
        warningInfo: '',
        imagePath: require('./assets/beaches/boscombe_east.png'),
    },
    {
        id: 3,
        name: 'Boscombe Beach West',
        latitude: 50.719702,
        longitude: -1.845608,
        latitudeParking: 50.720522,
        longitudeParking: -1.842338,
        beachStatus: Constants.statuses.avoid,
        lifeguarded: false,
        publicToilets: true,
        parkingAvailability: Constants.parking.availability + '43%',
        dogWalking: false,
        cycling: false,
        warningInfo: '',
        bbq: Constants.bbq.designedArea,
        imagePath: require('./assets/beaches/boscombe_west.png'),
    },
    {
        id: 4,
        name: 'Bournemouth Beach East',
        latitude: 50.716826,
        longitude: -1.870989,
        latitudeParking: 50.71707,
        longitudeParking: -1.873347,
        beachStatus: Constants.statuses.avoid,
        lifeguarded: true,
        publicToilets: true,
        parkingAvailability: Constants.parking.availability + '23%',
        dogWalking: false,
        cycling: false,
        warningInfo: '',
        bbq: Constants.bbq.designedArea,
        imagePath: require('./assets/beaches/bournemouth_east.png'),
    },
    {
        id: 5,
        name: 'Bournemouth Beach West',
        latitude: 50.71533,
        longitude: -1.878462,
        latitudeParking: 50.717687,
        longitudeParking: -1.881558,
        beachStatus: Constants.statuses.avoid,
        lifeguarded: true,
        publicToilets: true,
        parkingAvailability: Constants.parking.availability + '26%',
        dogWalking: false,
        cycling: false,
        warningInfo: '',
        bbq: Constants.bbq.afterSix,
        imagePath: require('./assets/beaches/bournemouth_west.png'),
    },
    {
        id: 6,
        name: 'Branksome Chine',
        latitude: -1.909293,
        longitude: -1.909293,
        latitudeParking: 50.706591,
        longitudeParking: -1.90951,
        beachStatus: Constants.statuses.congested,
        lifeguarded: false,
        publicToilets: true,
        parkingAvailability: Constants.parking.availability + '56%',
        dogWalking: true,
        cycling: true,
        warningInfo: '',
        bbq: Constants.bbq.afterSix,
        imagePath: require('./assets/beaches/branksome_chine.png'),
    },
    {
        id: 7,
        name: 'Branksome Dene Chine',
        latitude: 50.708673,
        longitude: -1.903423,
        latitudeParking: 50.709793,
        longitudeParking: -1.903231,
        beachStatus: Constants.statuses.congested,
        lifeguarded: false,
        publicToilets: true,
        parkingAvailability: Constants.parking.availability + '57%',
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.afterSix,
        warningInfo: '',
        imagePath: require('./assets/beaches/branksome_dene_chine.png'),
    },
    {
        id: 8,
        name: 'Canford Cliffs',
        latitude: 50.701117,
        longitude: -1.920114,
        latitudeParking: 50.706095,
        longitudeParking: -1.914312,
        beachStatus: Constants.statuses.avoid,
        lifeguarded: false,
        publicToilets: true,
        parkingAvailability: Constants.parking.notAvailable,
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.afterSix,
        warningInfo:
            'Cliff stabilisation works are taking place in this area. There may be limited access along the promenade at times.',
        imagePath: require('./assets/beaches/canford_cliffs.png'),
    },
    {
        id: 9,
        name: 'Durley Chine',
        latitude: 50.71328,
        longitude: -1.889044,
        latitudeParking: 50.714763,
        longitudeParking: -1.890673,
        beachStatus: Constants.statuses.congested,
        lifeguarded: false,
        publicToilets: true,
        parkingAvailability: Constants.parking.availability + '66%',
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.afterSix,
        warningInfo: '',
        imagePath: require('./assets/beaches/durley_chine.png'),
    },
    {
        id: 10,
        name: 'East Cliff',
        latitude: 50.71765,
        longitude: -1.865269,
        latitudeParking: 50.721464,
        longitudeParking: -1.864163,
        beachStatus: Constants.statuses.avoid,
        lifeguarded: false,
        publicToilets: false,
        parkingAvailability: Constants.parking.notAvailable,
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.afterSix,
        warningInfo: '',
        imagePath: require('./assets/beaches/east_cliff.png'),
    },
    {
        id: 11,
        name: 'Fishermans Walk',
        latitude: 50.720874,
        longitude: -1.817272,
        latitudeParking: 50.721915,
        longitudeParking: -1.819807,
        beachStatus: Constants.statuses.congested,
        lifeguarded: false,
        publicToilets: true,
        parkingAvailability: Constants.parking.notAvailable,
        dogWalking: true,
        cycling: false,
        bbq: Constants.bbq.afterSix,
        warningInfo: '',
        imagePath: require('./assets/beaches/fishermans_walk.png'),
    },
    {
        id: 12,
        name: 'Flaghead Chine',
        latitude: 50.697792,
        longitude: -1.925335,
        latitudeParking: 50.694871,
        longitudeParking: -1.931001,
        beachStatus: Constants.statuses.lowCongestion,
        lifeguarded: false,
        publicToilets: false,
        parkingAvailability: Constants.parking.notAvailable,
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.afterSix,
        warningInfo: '',
        imagePath: require('./assets/beaches/flaghead_chine.png'),
    },
    {
        id: 13,
        name: "Friar's Cliff",
        latitude: 50.733391,
        longitude: -1.727219,
        latitudeParking: 50.73442,
        longitudeParking: -1.73039,
        beachStatus: Constants.statuses.avoid,
        lifeguarded: false,
        publicToilets: true,
        parkingAvailability: Constants.parking.availability + '50%',
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.notAllowed,
        warningInfo: '',
        imagePath: require('./assets/beaches/friars_cliff.png'),
    },
    {
        id: 14,
        name: 'Highcliffe Beach',
        latitude: 50.737042,
        longitude: -1.695842,
        latitudeParking: 50.738285,
        longitudeParking: -1.696174,
        beachStatus: Constants.statuses.avoid,
        lifeguarded: false,
        publicToilets: false,
        parkingAvailability: Constants.parking.availability + '90%',
        dogWalking: true,
        cycling: false,
        bbq: Constants.bbq.afterSix,
        warningInfo: '',
        imagePath: require('./assets/beaches/highcliffe.png'),
    },
    {
        id: 15,
        name: 'Highcliffe Castle',
        latitude: 50.735906,
        longitude: -1.715519,
        latitudeParking: 50.737106,
        longitudeParking: -1.714311,
        beachStatus: Constants.statuses.avoid,
        lifeguarded: false,
        publicToilets: false,
        parkingAvailability: Constants.parking.availability + '20%',
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.designedArea,
        warningInfo: '',
        imagePath: require('./assets/beaches/highcliffe_castle.png'),
    },
    {
        id: 16,
        name: 'Manor Steps',
        latitude: 50.720507,
        longitude: -1.833951,
        latitudeParking: 50.721605,
        longitudeParking: -1.83219,
        beachStatus: Constants.statuses.congested,
        lifeguarded: false,
        publicToilets: true,
        parkingAvailability: Constants.parking.notAvailable,
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.afterSix,
        warningInfo: '',
        imagePath: require('./assets/beaches/manor_steps.png'),
    },
    {
        id: 17,
        name: 'Middle Chine',
        latitude: 50.712306,
        longitude: -1.892246,
        latitudeParking: 50.714138,
        longitudeParking: -1.890524,
        beachStatus: Constants.statuses.lowCongestion,
        lifeguarded: false,
        publicToilets: false,
        parkingAvailability: Constants.parking.notAvailable,
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.afterSix,
        warningInfo: '',
        imagePath: require('./assets/beaches/middle_chine.png'),
    },
    {
        id: 18,
        name: 'Mudeford Quay',
        latitude: 50.726982,
        longitude: -1.736977,
        latitudeParking: 50.725055,
        longitudeParking: -1.740131,
        beachStatus: Constants.statuses.lowCongestion,
        lifeguarded: false,
        publicToilets: false,
        parkingAvailability: Constants.parking.availability + '70%',
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.notAllowed,
        warningInfo: '',
        imagePath: require('./assets/beaches/mudeford_quay.png'),
    },
    {
        id: 19,
        name: 'Mudeford Sandspit',
        latitude: 50.716286,
        longitude: -1.745449,
        latitudeParking: 50.719319,
        longitudeParking: -1.770699,
        beachStatus: Constants.statuses.lowCongestion,
        lifeguarded: false,
        publicToilets: false,
        parkingAvailability: Constants.parking.availability + '80%',
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.afterSix,
        warningInfo: '',
        imagePath: require('./assets/beaches/mudeford_sandspit.png'),
    },
    {
        id: 20,
        name: 'Sandbanks',
        latitude: 50.688716,
        longitude: -1.937773,
        latitudeParking: 50.688782,
        longitudeParking: -1.939079,
        beachStatus: Constants.statuses.avoid,
        lifeguarded: true,
        publicToilets: true,
        parkingAvailability: Constants.parking.availability + '40%',
        dogWalking: false,
        cycling: false,
        bbq: Constants.bbq.designedArea,
        warningInfo: '',
        imagePath: require('./assets/beaches/sandbanks.png'),
    },
    {
        id: 21,
        name: 'Shore Road',
        latitude: 50.698326,
        longitude: -1.933059,
        latitudeParking: 50.688782,
        longitudeParking: -1.939079,
        beachStatus: Constants.statuses.lowCongestion,
        lifeguarded: false,
        publicToilets: true,
        parkingAvailability: Constants.parking.notAvailable,
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.afterSix,
        warningInfo: '',
        imagePath: require('./assets/beaches/shore_road.png'),
    },
    {
        id: 22,
        name: 'Solent Beach',
        latitude: 50.717803,
        longitude: -1.778109,
        latitudeParking: 50.719029,
        longitudeParking: -1.7779,
        beachStatus: Constants.statuses.congested,
        lifeguarded: false,
        publicToilets: false,
        parkingAvailability: Constants.parking.availability + '80%',
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.notAllowed,
        warningInfo: '',
        imagePath: require('./assets/beaches/solent.png'),
    },
    {
        id: 23,
        name: 'Southbourne Beach',
        latitude: 50.719227,
        longitude: -1.793017,
        latitudeParking: 50.719846,
        longitudeParking: -1.794108,
        beachStatus: Constants.statuses.lowCongestion,
        lifeguarded: false,
        publicToilets: true,
        parkingAvailability: Constants.parking.availability + '20%',
        dogWalking: true,
        cycling: true,
        bbq: Constants.bbq.designedArea,
        warningInfo: '',
        imagePath: require('./assets/beaches/southbourne.png'),
    },
];

const getBeaches = () => {
    return beaches;
};

export default getBeaches;
