// This file contains all the data about the beaches

const beaches = [
  {
    id: "0",
    beachName: "Alum Chine",
    beachStatus: "Low congestion",
    lifeguarded: "Yes",
    publicToilets: "Yes",
    parkingAvailability: "80%",
    dogWalking: "Yes",
    cycling: "Yes",
    bbq: "Yes",
    warningInfo:
      "Cliff stabilisation works are taking place in this area. There may be limited access along the promenade at times.",
    imagePath: require("./assets/beaches/alumn_chine.png"),
  },
  {
    id: "1",
    beachName: "Avon Beach",
    beachStatus: "Status not available",
    lifeguarded: "",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    warningInfo: "",
    imagePath: require("./assets/beaches/avon.png"),
  },
  {
    id: "2",
    beachName: "Boscombe Beach East",
    beachStatus: "Avoid",
    lifeguarded: "",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/boscombe_east.png"),
  },
  {
    id: "3",
    beachName: "Boscombe Beach West",
    beachStatus: "Avoid",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/boscombe_west.png"),
  },
  {
    id: "4",
    beachName: "Bournemouth Beach East",
    beachStatus: "Avoid",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/bournemouth_east.png"),
  },
  {
    id: "5",
    beachName: "Bournemouth Beach West",
    beachStatus: "Avoid",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/bournemouth_west.png"),
  },
  {
    id: "6",
    beachName: "Branksome Chine",
    beachStatus: "Congested, stay alert",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/branksome_chine.png"),
  },
  {
    id: "7",
    beachName: "Branksome Dene Chine",
    beachStatus: "Congested, stay alert",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/branksome_dene_chine.png"),
  },
  {
    id: "8",
    beachName: "Canford Cliffs",
    beachStatus: "Avoid",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/canford_cliffs.png"),
  },
  {
    id: "9",
    beachName: "Durley Chine",
    beachStatus: "Congested, stay alert",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/durley_chine.png"),
  },
  {
    id: "10",
    beachName: "East Cliff",
    beachStatus: "Avoid",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/east_cliff.png"),
  },
  {
    id: "11",
    beachName: "Fishermans Walk",
    beachStatus: "Congested, stay alert",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/fishermans_walk.png"),
  },
  {
    id: "12",
    beachName: "Flaghead Chine",
    beachStatus: "Low congestion",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/flaghead_chine.png"),
  },
  {
    id: "13",
    beachName: "Friar's Cliff",
    beachStatus: "Avoid",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/friars_cliff.png"),
  },
  {
    id: "14",
    beachName: "Highcliffe Beach",
    beachStatus: "Avoid",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/highcliffe.png"),
  },
  {
    id: "15",
    beachName: "Highcliffe Castle",
    beachStatus: "Avoid",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/highcliffe_castle.png"),
  },
  {
    id: "16",
    beachName: "Manor Steps",
    beachStatus: "Congested, stay alert",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/manor_steps.png"),
  },
  {
    id: "17",
    beachName: "Middle Chine",
    beachStatus: "Low congestion",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/middle_chine.png"),
  },
  {
    id: "18",
    beachName: "Mudeford Quay",
    beachStatus: "Low congestion",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/mudeford_quay.png"),
  },
  {
    id: "19",
    beachName: "Mudeford Sandspit",
    beachStatus: "Low congestion",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/mudeford_sandspit.png"),
  },
  {
    id: "20",
    beachName: "Sandbanks",
    beachStatus: "Avoid",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/sandbanks.png"),
  },
  {
    id: "21",
    beachName: "Shore Road",
    beachStatus: "Low congestion",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/shore_road.png"),
  },
  {
    id: "22",
    beachName: "Solent Beach",
    beachStatus: "Congested, stay alert",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/solent.png"),
  },
  {
    id: "23",
    beachName: "Southbourne Beach",
    beachStatus: "Status not available",
    lifeguarded: "No",
    publicToilets: "No",
    parkingAvailability: "20%",
    dogWalking: "No",
    cycling: "No",
    bbq: "No",
    imagePath: require("./assets/beaches/southbourne.png"),
  },
];

const getBeaches = () => {
  return beaches;
};

export default getBeaches;
